### ISSUE TITLE
Need better Guide! What does the hardware setup look like?

### ISSUE THREAD

**Issue by Apprisco** [oldhui-uk/tftbridge#4]
Hi, I have the TFT35 fully wired on to the SKR Mini E3 V3.0.
I have no clue how to set this up, software side it seems fine but hardware side things are not working.
Do I have to wire the 5 pin cable to the pi?

**Comment by StarNamer** [comment]
See here: https://oldhui.wordpress.com/2024/01/28/using-btt-tft35-with-klipper-in-touch-mode/

**Comment by Apprisco** [comment]
> See here: https://oldhui.wordpress.com/2024/01/28/using-btt-tft35-with-klipper-in-touch-mode/

How did you find the serial? I found the klipper . serial but not the port in my rpi.

**Comment by Apprisco** [comment]
There's lots of them on my rpi including AMA0 but setting it to AMA0 I never get a connection.
